GET http://localhost:8085/ebook/List?page=1&size=1001

###



POST http://localhost:8085/ebook/save
Content-Type: application/json

{}

###

POST http://localhost:8085/api/item
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###